"""
graph_view.py — Qt scene/view layer for NodesImport.

SLOT CONVENTION: see parsing.py module docstring. Must stay in sync.
"""

import os
import re
import tempfile
import typing

# ---------------------------------------------------------------------------
# Qt compatibility — supports PySide2 (Nuke ≤15) and PySide6 (Nuke 16+)
# ---------------------------------------------------------------------------
try:
    from PySide6 import QtWidgets, QtCore, QtGui  # type: ignore
    _PYSIDE_VERSION = 6
except ImportError:
    from PySide2 import QtWidgets, QtCore, QtGui  # type: ignore
    _PYSIDE_VERSION = 2

try:
    import nuke  # type: ignore
except ImportError:
    nuke = None

# Must match _NULL_INPUT in parsing.py
_NULL_INPUT: int = -1

# Node types treated as backdrop rectangles in the scene
_BACKDROP_TYPES: frozenset = frozenset({"backdrop", "backdropnode"})

# Node types whose internal set/push variables must be rewritten on export
_FLAT_GROUP_TYPES: frozenset = frozenset({"group", "livegroup", "gizmo"})

# Display/terminal nodes — not shown in the graph and excluded from import.
# Must stay in sync with _STACK_EXEMPT_TYPES in parsing.py.
_STACK_EXEMPT_TYPES: frozenset = frozenset({"viewer", "colorspace"})

# Node types that are internal/auto-generated by Nuke and should be hidden
# from the graph view. Their connections are drawn through them transparently
# so the visual graph remains clean without losing connection information.
_HIDDEN_NODE_TYPES: frozenset = frozenset({"add_layer"})


# ---------------------------------------------------------------------------
# Variable rewriter for Group / Gizmo content
# ---------------------------------------------------------------------------

def _rewrite_group_vars(content: str, node_name: str, counter: typing.List[int]) -> str:
    """
    Rewrite internal set/push variable names inside a Group/Gizmo content
    blob to fresh unique names.

    WHY: Group nodes in Format B contain internal `set N5757400 [stack 0]`
    and `push $N5757400` directives where the variable names are memory
    addresses from the original Nuke session.  When exported to a temp file,
    any `push $VAR` that references a variable defined OUTSIDE this Group
    would be undefined, causing Nuke to push nothing and break all internal
    connections.

    This function renames every `set`-defined variable to a fresh unique
    name (`GV_{node}_{n}`) and updates all matching `push $` references.
    Variables that are pushed but never set in this block (external inputs)
    are left unchanged — the outer write-stack handles those.
    """
    set_re = re.compile(r"(^set\s+)(\w+)(\s+\[stack\s+\d+\])", re.MULTILINE)
    old_to_new: typing.Dict[str, str] = {}

    def _replace_set(m: re.Match) -> str:  # type: ignore[type-arg]
        old = m.group(2)
        if old not in old_to_new:
            safe = re.sub(r"\W", "_", node_name)
            old_to_new[old] = f"GV_{safe}_{counter[0]}"
            counter[0] += 1
        return m.group(1) + old_to_new[old] + m.group(3)

    content = set_re.sub(_replace_set, content)
    for old, new in old_to_new.items():
        content = re.sub(r"(push\s+\$)" + re.escape(old) + r"\b", r"\g<1>" + new, content)
    return content


# ---------------------------------------------------------------------------
# EdgeItem
# ---------------------------------------------------------------------------

class EdgeItem(QtWidgets.QGraphicsPathItem):
    """
    Connection line from a parent node's output (bottom-centre) to a child
    node's specific input slot (top edge), matching Nuke's wiring convention.

    Slot positions along the child's top edge:
      - 1 input  → centre
      - 2 inputs → left-third, right-third  (matching Nuke's A/B layout)
      - N inputs → evenly distributed across the top edge
    """

    _PEN = QtGui.QPen(QtGui.QColor(160, 160, 160), 1.2, QtCore.Qt.SolidLine)

    def __init__(
        self,
        parent_item: "NodeItem",
        child_item:  "NodeItem",
        slot:        int = 0,
        num_slots:   int = 1,
    ) -> None:
        super().__init__()
        self.parent_item = parent_item
        self.child_item  = child_item
        self._slot      = slot
        self._num_slots = max(num_slots, 1)
        self.setFlag(QtWidgets.QGraphicsItem.ItemIsSelectable, False)
        self.setZValue(-1)
        self.setPen(self._PEN)
        self._update_path()

    def _slot_x(self, rect: QtCore.QRectF, slot: int, num_slots: int) -> float:
        """Return the scene X coordinate for a given slot along a node's top edge."""
        if num_slots <= 1:
            return rect.center().x()
        # Distribute evenly: slot 0 at left edge + half-division width,
        # last slot at right edge - half-division width
        division = rect.width() / num_slots
        return rect.left() + division * slot + division * 0.5

    def _update_path(self) -> None:
        pr = self.parent_item.sceneBoundingRect()
        cr = self.child_item.sceneBoundingRect()

        # Output: bottom-centre of parent (DotItem uses centre)
        if isinstance(self.parent_item, DotItem):
            src = pr.center()
        else:
            src = QtCore.QPointF(pr.center().x(), pr.bottom())

        # Input: correct slot position on child's top edge (DotItem uses centre)
        if isinstance(self.child_item, DotItem):
            dst = cr.center()
        else:
            dst = QtCore.QPointF(
                self._slot_x(cr, self._slot, self._num_slots),
                cr.top(),
            )

        path = QtGui.QPainterPath(src)
        path.lineTo(dst)
        self.setPath(path)




# ---------------------------------------------------------------------------
# DotItem  — Dot nodes rendered as small circles, no label
# ---------------------------------------------------------------------------

class DotItem(QtWidgets.QGraphicsEllipseItem):
    """
    Dot nodes are rendered as small filled circles (12×12 px), matching
    Nuke's own DAG style. No label is shown. The circle is centred on the
    node's (xpos, ypos) coordinate so edges connect naturally.
    """
    _SIZE = 12

    def __init__(self, node_data: typing.Any) -> None:
        r = self._SIZE / 2
        super().__init__(-r, -r, self._SIZE, self._SIZE)
        self.node_data = node_data
        # In Nuke's .nk format, Dot xpos/ypos is the CENTRE of the dot
        # (unlike regular nodes where it is the top-left of the rect).
        self.setPos(node_data.xpos, node_data.ypos)
        self.setFlag(QtWidgets.QGraphicsItem.ItemIsSelectable)
        self.setFlag(QtWidgets.QGraphicsItem.ItemIsMovable)
        self.setZValue(0)
        self.setBrush(QtGui.QBrush(QtGui.QColor(90, 90, 90)))
        self.setPen(QtGui.QPen(QtGui.QColor(140, 140, 140), 1.5))
        self._deselect_preview: bool = False

    def paint(
        self,
        painter: QtGui.QPainter,
        option:  QtWidgets.QStyleOptionGraphicsItem,
        widget:  typing.Optional[QtWidgets.QWidget] = None,
    ) -> None:
        option.state &= ~QtWidgets.QStyle.State_Selected  # type: ignore[operator]
        super().paint(painter, option, widget)
        r = self._SIZE / 2 + 2
        if self._deselect_preview:
            painter.setPen(QtGui.QPen(QtGui.QColor(200, 120, 30), 2))
            painter.setBrush(QtCore.Qt.NoBrush)
            painter.drawEllipse(QtCore.QRectF(-r, -r, r * 2, r * 2))
        elif self.isSelected():
            painter.setPen(QtGui.QPen(QtGui.QColor(255, 210, 0), 2))
            painter.setBrush(QtCore.Qt.NoBrush)
            painter.drawEllipse(QtCore.QRectF(-r, -r, r * 2, r * 2))

# ---------------------------------------------------------------------------
# BackdropItem
# ---------------------------------------------------------------------------

class BackdropItem(QtWidgets.QGraphicsRectItem):
    """
    Semi-transparent selectable backdrop rectangle.
    Sized from bdwidth/bdheight knobs. Fill is tile_color at 20% alpha.
    Sits at zValue -2 (behind edges and nodes).
    Backdrops can be selected and imported just like regular nodes.
    """

    def __init__(self, node_data: typing.Any) -> None:
        super().__init__()
        self.node_data = node_data

        w_m  = re.search(r"^\s*bdwidth\s+(\d+)",        node_data.content, re.MULTILINE)
        h_m  = re.search(r"^\s*bdheight\s+(\d+)",       node_data.content, re.MULTILINE)
        l_m  = re.search(r"^\s*label\s+(.+)",           node_data.content, re.MULTILINE)
        fs_m = re.search(r"^\s*note_font_size\s+(\d+)", node_data.content, re.MULTILINE)

        width  = int(w_m.group(1))  if w_m  else 200
        height = int(h_m.group(1))  if h_m  else 100
        raw_label = l_m.group(1).strip().strip('"').strip("'") if l_m else ""
        # Strip HTML tags, then unescape \n and \t escape sequences
        label = re.sub(r"<[^>]+>", "", raw_label).strip()
        label = label.replace("\\n", "\n").replace("\\t", "\t")
        font_size = min(int(fs_m.group(1)), 18) if fs_m else 14

        self.setRect(0, 0, width, height)
        self.setPos(node_data.xpos, node_data.ypos)
        # Backdrops are NOT natively selectable by Qt — we manage their
        # selection state manually in GraphView.mouseReleaseEvent so we can
        # enforce full-containment semantics (a backdrop is only selected when
        # the rubber-band completely encloses it, never on a partial touch or
        # single click).  ItemIsSelectable is deliberately omitted so Qt's
        # rubber-band and click handlers never select a backdrop on their own.
        # ItemIsSelectable=True lets setSelected() work so our import logic
        # can mark backdrops as selected. But we set AcceptedMouseButtons to
        # NoButton so Qt's own click/rubber-band handler never selects a backdrop
        # directly — we manage that entirely in GraphView.mouseReleaseEvent with
        # the full-containment rule.
        self.setFlag(QtWidgets.QGraphicsItem.ItemIsSelectable)
        self.setFlag(QtWidgets.QGraphicsItem.ItemIsMovable, False)
        self.setZValue(-2)
        self.setAcceptedMouseButtons(QtCore.Qt.NoButton)

        self._base = self._base_color()
        fill   = QtGui.QColor(self._base); fill.setAlpha(51)    # 20%
        border = QtGui.QColor(self._base); border.setAlpha(153) # 60%
        self.setBrush(QtGui.QBrush(fill))
        self._normal_pen         = QtGui.QPen(border, 2)
        self._selected_pen       = QtGui.QPen(QtGui.QColor(255, 210, 0), 3)
        self._deselect_prev_pen  = QtGui.QPen(QtGui.QColor(200, 120, 30), 3)
        self.setPen(self._normal_pen)
        self._deselect_preview: bool = False

        if label:
            self.label = QtWidgets.QGraphicsTextItem(label, self)
            self.label.setDefaultTextColor(QtGui.QColor(255, 255, 255, 200))
            font = self.label.font()
            font.setPointSize(font_size)
            font.setBold(True)
            self.label.setFont(font)
            self.label.setPos(8, 4)
            self.label.setTextWidth(float(width - 16))
            # Label must not intercept mouse events — clicks should pass
            # through to the view so nodes inside the backdrop are reachable.
            self.label.setFlag(QtWidgets.QGraphicsItem.ItemIsSelectable, False)
            self.label.setAcceptedMouseButtons(QtCore.Qt.NoButton)
            self.label.setAcceptHoverEvents(False)

    def _base_color(self) -> QtGui.QColor:
        if (
            hasattr(self.node_data, "tile_color")
            and self.node_data.tile_color is not None
        ):
            c = self.node_data.tile_color
            r, g, b, a = (c >> 24) & 0xFF, (c >> 16) & 0xFF, (c >> 8) & 0xFF, c & 0xFF
            if a > 0:
                return QtGui.QColor(r, g, b)
        return QtGui.QColor(80, 80, 80)

    def paint(
        self,
        painter: QtGui.QPainter,
        option:  QtWidgets.QStyleOptionGraphicsItem,
        widget:  typing.Optional[QtWidgets.QWidget] = None,
    ) -> None:
        option.state &= ~QtWidgets.QStyle.State_Selected  # type: ignore[operator]
        super().paint(painter, option, widget)
        if self._deselect_preview:
            painter.setPen(self._deselect_prev_pen)
            painter.setBrush(QtCore.Qt.NoBrush)
            painter.drawRect(self.rect())
        elif self.isSelected():
            painter.setPen(self._selected_pen)
            painter.setBrush(QtCore.Qt.NoBrush)
            painter.drawRect(self.rect())


# ---------------------------------------------------------------------------
# NodeItem
# ---------------------------------------------------------------------------

class NodeItem(QtWidgets.QGraphicsRectItem):
    def __init__(self, node_data: typing.Any) -> None:
        super().__init__()
        self.node_data = node_data

        is_group = node_data.node_type.lower() in _FLAT_GROUP_TYPES
        width  = 100 if is_group else 80
        height =  40 if is_group else 30
        self.setRect(0, 0, width, height)

        self.setFlag(QtWidgets.QGraphicsItem.ItemIsSelectable)
        self.setFlag(QtWidgets.QGraphicsItem.ItemIsMovable)

        color = self._get_color()
        self.setBrush(QtGui.QBrush(color))
        self.setPen(QtGui.QPen(QtGui.QColor(100, 100, 100), 2 if is_group else 1))

        self.label = QtWidgets.QGraphicsTextItem(node_data.name, self)
        tc = QtGui.QColor(255, 255, 255) if color.lightness() < 128 else QtGui.QColor(0, 0, 0)
        self.label.setDefaultTextColor(tc)
        font = self.label.font()
        font.setPointSize(7)
        font.setBold(is_group)
        self.label.setFont(font)
        lw = min(self.label.boundingRect().width(), float(width))
        lh = self.label.boundingRect().height()
        self.label.setPos((width - lw) / 2.0, (height - lh) / 2.0)
        self.label.setTextWidth(float(width))

        self.setPos(node_data.xpos, node_data.ypos)
        self._deselect_preview: bool = False  # True while inside a Ctrl+Drag band

    def _get_color(self) -> QtGui.QColor:
        if (
            hasattr(self.node_data, "tile_color")
            and self.node_data.tile_color is not None
        ):
            c = self.node_data.tile_color
            r, g, b, a = (c >> 24) & 0xFF, (c >> 16) & 0xFF, (c >> 8) & 0xFF, c & 0xFF
            if a > 0:
                return QtGui.QColor(r, g, b, a)

        nt = self.node_data.node_type.lower()
        for keywords, color in _COLOR_MAP:
            if any(kw in nt for kw in keywords):
                return color
        return QtGui.QColor(60, 60, 60)

    def paint(
        self,
        painter: QtGui.QPainter,
        option:  QtWidgets.QStyleOptionGraphicsItem,
        widget:  typing.Optional[QtWidgets.QWidget] = None,
    ) -> None:
        option.state &= ~QtWidgets.QStyle.State_Selected  # type: ignore[operator]
        super().paint(painter, option, widget)
        if self._deselect_preview:
            # Dim orange ring: "this node will be deselected on release"
            painter.setPen(QtGui.QPen(QtGui.QColor(200, 120, 30), 2))
            painter.setBrush(QtCore.Qt.NoBrush)
            painter.drawRect(self.rect())
        elif self.isSelected():
            painter.setPen(QtGui.QPen(QtGui.QColor(255, 210, 0), 2))
            painter.setBrush(QtCore.Qt.NoBrush)
            painter.drawRect(self.rect())


# Colour lookup table — ordered most-specific first to prevent substring collisions
_COLOR_MAP: typing.List[typing.Tuple[typing.List[str], QtGui.QColor]] = [
    (["deep"],                                          QtGui.QColor( 30,  40,  70)),
    (["roto", "bezier", "rotopaint"],                   QtGui.QColor(140, 190, 140)),
    (["rectangle", "flood", "radial", "ramp"],          QtGui.QColor(180, 180, 180)),
    (["correct", "grade", "invert", "multiply",
      "hsv", "saturation", "lookup", "clamp",
      "colorcorrect", "colorlookup"],                   QtGui.QColor(120, 160, 250)),
    (["ocio"],                                          QtGui.QColor( 40, 180, 180)),
    (["time", "retiming", "frameholdon",
      "frameblend", "temporalmediann"],                 QtGui.QColor(200, 190, 140)),
    (["copycat", "bigcat"],                             QtGui.QColor(180,  80, 120)),
    (["shuffle", "remove", "addchannels"],              QtGui.QColor(180,  80, 120)),
    (["merge", "mix"],                                  QtGui.QColor( 75, 122, 191)),
    (["keyer", "matte", "primatte", "ibk"],             QtGui.QColor(  0, 200,  80)),
    (["write"],                                         QtGui.QColor(255, 220,   0)),
    (["blur", "erode", "glow", "sharpen",
      "median", "laplacian", "soften",
      "denoise", "grain"],                              QtGui.QColor(240, 140,  80)),
    (["transform", "mirror", "crop", "distort",
      "resize", "position", "stabilize",
      "corner", "lensdistortion"],                      QtGui.QColor(180, 140, 200)),
    (["group", "livegroup", "gizmo"],                   QtGui.QColor( 51,  51,  51)),
    (["read"],                                          QtGui.QColor(255, 165,   0)),
    (["text", "stickynote"],                            QtGui.QColor(200, 200, 200)),
    (["dot"],                                           QtGui.QColor( 80,  80,  80)),
]


# ---------------------------------------------------------------------------
# GraphView
# ---------------------------------------------------------------------------

class GraphView(QtWidgets.QGraphicsView):

    # A very large scene rect gives an effectively infinite canvas.
    # Qt requires *some* finite rect for the scene, so we use ±1,000,000 units.
    # setSceneRect() is called once with this value and never changed, so the
    # scene never auto-shrinks when items are removed (which would cause the
    # view to jump). Panning is unconstrained within these bounds.
    _INFINITE = 1_000_000

    def __init__(self, parent: typing.Optional[QtWidgets.QWidget] = None) -> None:
        super().__init__(parent)
        self.scene = QtWidgets.QGraphicsScene(self)
        self.setScene(self.scene)
        self.setRenderHint(QtGui.QPainter.Antialiasing)
        self.setDragMode(QtWidgets.QGraphicsView.RubberBandDrag)
        self.setBackgroundBrush(QtGui.QBrush(QtGui.QColor(35, 35, 35)))
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # Accept keyboard events (required for F key framing)
        self.setFocusPolicy(QtCore.Qt.StrongFocus)
        # Accept tablet events
        self.setAttribute(QtCore.Qt.WA_TabletTracking, True)
        self.viewport().setAttribute(QtCore.Qt.WA_TabletTracking, True)

        # Fix the scene rect to a huge value — this is what gives the infinite
        # canvas feel. Without this Qt auto-resizes the scene to fit items,
        # causing the view to snap/jump when panning near the content edges.
        inf = self._INFINITE
        self.scene.setSceneRect(-inf, -inf, inf * 2, inf * 2)

        self._is_zooming       = False
        self._middle_held      = False
        self._last_pos         = QtCore.QPoint()
        self._zoom_anchor      = QtCore.QPoint()
        self._pre_drag_sel:    typing.Set[QtWidgets.QGraphicsItem] = set()
        self._drag_modifier    = QtCore.Qt.NoModifier
        self._drag_start_pos   = QtCore.QPoint()  # viewport pos where rubber-band started

    # ── Keyboard ─────────────────────────────────────────────────────────────

    def keyPressEvent(self, event: QtGui.QKeyEvent) -> None:
        """
        F       — frame view: nothing selected → fit all; selected → fit selection
        Ctrl+A  — select all nodes, dots and backdrops
        """
        if event.key() == QtCore.Qt.Key_F:
            selected = [i for i in self.scene.selectedItems() if isinstance(i, NodeItem)]
            if selected:
                bounds = selected[0].sceneBoundingRect()
                for item in selected[1:]:
                    bounds = bounds.united(item.sceneBoundingRect())
            else:
                bounds = QtCore.QRectF()
                for item in self.scene.items():
                    if isinstance(item, NodeItem):
                        r = item.sceneBoundingRect()
                        bounds = bounds.united(r) if not bounds.isNull() else r
                if bounds.isNull():
                    bounds = self.scene.itemsBoundingRect()
            # Add a comfortable margin around the content when framing
            M = 200
            self.fitInView(bounds.adjusted(-M, -M, M, M), QtCore.Qt.KeepAspectRatio)
            event.accept()
            return

        if event.key() == QtCore.Qt.Key_A and event.modifiers() == QtCore.Qt.ControlModifier:
            for item in self.scene.items():
                if isinstance(item, (NodeItem, DotItem, BackdropItem)):
                    item.setSelected(True)
            event.accept()
            return

        if event.key() in (QtCore.Qt.Key_Return, QtCore.Qt.Key_Enter):
            self.import_selected()
            event.accept()
            return

        super().keyPressEvent(event)

    # ── Tablet / Wacom ───────────────────────────────────────────────────────

    def tabletEvent(self, event: QtGui.QTabletEvent) -> None:
        """Force Qt to re-deliver tablet events as mouse events."""
        event.ignore()

    # ── Mouse navigation ─────────────────────────────────────────────────────
    #
    # NAVIGATION
    #   Scroll wheel                  → zoom anchored under cursor
    #   Alt + LMB drag                → pan
    #   Middle drag                   → pan
    #   Middle held + tip pressed     → scrubby zoom (horizontal drag / Wacom)
    #   Ctrl + Alt + LMB drag         → scrubby zoom (mouse fallback)
    #
    # SELECTION
    #   LMB click on empty space      → deselect all
    #   LMB click on node             → select that node, deselect rest
    #   LMB drag                      → rubber-band, replace selection
    #   Shift + LMB click on node     → toggle that node's selection
    #   Shift + LMB drag              → rubber-band toggle:
    #                                     selected + in band → deselected
    #                                     not selected + in band → selected
    #   Ctrl + A                      → select all
    #   F                             → frame selection or all nodes
    #
    # BACKDROPS
    #   Never selected by click or partial band — only when band fully contains them

    def wheelEvent(self, event: QtGui.QWheelEvent) -> None:
        """
        Scroll wheel → zoom anchored under cursor.

        Critical: set AnchorUnderMouse BEFORE scale(), call event.accept(),
        and do NOT call super().wheelEvent() — doing so causes the view to
        pan after scaling, making the anchor point drift on every scroll tick.
        The anchor is left as AnchorUnderMouse permanently; this is fine
        because all panning paths (Alt+LMB, Middle drag) use translate()
        directly and are unaffected by the transformation anchor setting.
        """
        if event.modifiers() == QtCore.Qt.NoModifier:
            factor = 1.15 if event.angleDelta().y() > 0 else 1.0 / 1.15
            self.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
            self.scale(factor, factor)
            event.accept()
        else:
            super().wheelEvent(event)

    def mousePressEvent(self, event: QtGui.QMouseEvent) -> None:
        self._last_pos = event.pos()

        # Middle → pan (or zoom if tip also held)
        if event.button() == QtCore.Qt.MiddleButton:
            self._middle_held = True
            self.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
            # Freeze the current selection before sending the fake LMB event
            # that activates ScrollHandDrag — without this Qt clears the
            # selection as a side effect of the left-button press.
            frozen = self.scene.selectedItems()
            fake = QtGui.QMouseEvent(
                event.type(), event.pos(),
                QtCore.Qt.LeftButton, QtCore.Qt.LeftButton,
                event.modifiers(),
            )
            super().mousePressEvent(fake)
            # Restore selection immediately after
            for item in self.scene.items():
                item.setSelected(item in frozen)
            return

        # Tip while middle held → switch to scrubby zoom
        if event.button() == QtCore.Qt.LeftButton and self._middle_held:
            self.setDragMode(QtWidgets.QGraphicsView.RubberBandDrag)
            self._is_zooming = True
            self._zoom_anchor = event.pos()
            self.setCursor(QtCore.Qt.SizeHorCursor)
            event.accept()
            return

        # Ctrl + Alt + LMB → scrubby zoom
        if (
            event.button() == QtCore.Qt.LeftButton
            and event.modifiers() == (QtCore.Qt.AltModifier | QtCore.Qt.ControlModifier)
        ):
            self._is_zooming = True
            self._zoom_anchor = event.pos()
            self.setCursor(QtCore.Qt.SizeHorCursor)
            event.accept()
            return

        # Alt + LMB → pan
        if event.button() == QtCore.Qt.LeftButton and event.modifiers() == QtCore.Qt.AltModifier:
            self.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
            frozen = self.scene.selectedItems()
            fake = QtGui.QMouseEvent(
                event.type(), event.pos(),
                event.button(), event.buttons(),
                QtCore.Qt.NoModifier,
            )
            super().mousePressEvent(fake)
            for item in self.scene.items():
                item.setSelected(item in frozen)
            return

        # Default → rubber-band select
        # Snapshot the current selection and modifier so mouseReleaseEvent
        # can apply add/remove logic after Qt finishes the rubber-band.
        # We always run Qt's rubber-band in Replace mode so it doesn't
        # apply its own Shift/Ctrl behaviour — we handle that ourselves.
        self._drag_modifier  = event.modifiers()
        self._drag_start_pos = event.pos()
        if event.modifiers() == QtCore.Qt.ShiftModifier:
            # Shift+drag: snapshot current selection for toggle logic on release.
            # Strip Shift so Qt's rubber-band runs in plain replace mode —
            # we apply Nuke's toggle semantics ourselves in mouseReleaseEvent.
            self._pre_drag_sel = set(self.scene.selectedItems())
            fake = QtGui.QMouseEvent(
                event.type(), event.pos(),
                event.button(), event.buttons(),
                QtCore.Qt.NoModifier,
            )
            self.setDragMode(QtWidgets.QGraphicsView.RubberBandDrag)
            super().mousePressEvent(fake)
        else:
            self._pre_drag_sel = set()
            self.setDragMode(QtWidgets.QGraphicsView.RubberBandDrag)
            super().mousePressEvent(event)

    def mouseMoveEvent(self, event: QtGui.QMouseEvent) -> None:
        if self._is_zooming:
            delta = event.pos() - self._last_pos
            self._last_pos = event.pos()
            zoom = max(0.1, 1.0 + delta.x() * 0.01)
            old_anchor = self.transformationAnchor()
            self.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
            anchor_scene = self.mapToScene(self._zoom_anchor)
            self.scale(zoom, zoom)
            anchor_new = self.mapFromScene(anchor_scene)
            delta_anchor = anchor_new - self._zoom_anchor
            self.translate(-delta_anchor.x() / self.transform().m11(),
                           -delta_anchor.y() / self.transform().m22())
            self.setTransformationAnchor(old_anchor)
            event.accept()

        elif self._drag_modifier == QtCore.Qt.ShiftModifier and self._pre_drag_sel:
            # Shift+drag toggle preview: items that WILL be toggled (either newly
            # selected or deselected) show an orange preview ring during the drag.
            # Items that will stay unchanged keep their current gold/no ring.
            fake_move = QtGui.QMouseEvent(
                event.type(), event.pos(),
                event.button(), event.buttons(),
                QtCore.Qt.NoModifier,
            )
            super().mouseMoveEvent(fake_move)

            band_rect  = QtCore.QRect(self._drag_start_pos, event.pos()).normalized()
            band_scene = self.mapToScene(band_rect).boundingRect()

            for item in self.scene.items():
                if not isinstance(item, (NodeItem, DotItem, BackdropItem)):
                    continue
                in_band      = band_scene.intersects(item.sceneBoundingRect())
                was_selected = item in self._pre_drag_sel
                # Preview: items that are selected-AND-in-band will be DEselected
                new_preview  = was_selected and in_band
                if item._deselect_preview != new_preview:
                    item._deselect_preview = new_preview
                    item.update()

        else:
            super().mouseMoveEvent(event)

    def mouseReleaseEvent(self, event: QtGui.QMouseEvent) -> None:
        if event.button() == QtCore.Qt.MiddleButton:
            self._middle_held = False
            self._is_zooming  = False
            self.setDragMode(QtWidgets.QGraphicsView.RubberBandDrag)
            self.setCursor(QtCore.Qt.ArrowCursor)
        if event.button() == QtCore.Qt.LeftButton:
            self._is_zooming = False
            self.setDragMode(QtWidgets.QGraphicsView.RubberBandDrag)
            self.setCursor(QtCore.Qt.ArrowCursor)

            # Clear any live deselect-preview rendering before applying final state
            for item in self.scene.items():
                if isinstance(item, (NodeItem, DotItem, BackdropItem)):
                    if item._deselect_preview:
                        item._deselect_preview = False
                        item.update()

            # Build the band rect in scene coordinates
            band_rect_vp    = QtCore.QRect(self._drag_start_pos, event.pos()).normalized()
            band_scene_rect = self.mapToScene(band_rect_vp).boundingRect()
            is_drag = (event.pos() - self._drag_start_pos).manhattanLength() > 4

            # Qt has set the scene selection to items touching the band.
            # BackdropItems have ItemIsSelectable=False so Qt never touches them.
            # We apply our own backdrop selection rule here: a backdrop is added
            # to the result only when the band FULLY contains it and it was a drag.
            band_items: typing.Set[QtWidgets.QGraphicsItem] = set()
            for item in self.scene.selectedItems():
                # Only NodeItem / DotItem land here (backdrops are non-selectable)
                band_items.add(item)

            # Evaluate backdrops separately with full-containment rule
            if is_drag:
                for item in self.scene.items():
                    if isinstance(item, BackdropItem):
                        if band_scene_rect.contains(item.sceneBoundingRect()):
                            band_items.add(item)

            if self._drag_modifier == QtCore.Qt.ShiftModifier:
                # Toggle: items in band that were already selected get DEselected,
                # items in band that were NOT selected get selected.
                # This matches Nuke's node graph Shift+drag behaviour exactly.
                final = self._pre_drag_sel.symmetric_difference(band_items)
                for item in self.scene.items():
                    item.setSelected(item in final)

            else:
                # Plain replace: use filtered band_items
                for item in self.scene.items():
                    item.setSelected(item in band_items)

            # Reset drag state
            self._pre_drag_sel   = set()
            self._drag_modifier  = QtCore.Qt.NoModifier
            self._drag_start_pos = QtCore.QPoint()

        super().mouseReleaseEvent(event)

    # ── Scene population ─────────────────────────────────────────────────────

    def load_nodes(self, nodes: typing.List[typing.Any]) -> None:
        """
        Populate the scene from a list of NukeNode objects.

        Three passes:
          1. Backdrops  (zValue -2, behind everything)
          2. Node boxes (zValue  0)
          3. Edges      (zValue -1, between backdrops and nodes)
        """
        self.scene.clear()
        # Store full parsed node list so import_selected can resolve hidden
        # intermediary nodes that are not present as scene items
        self._all_parsed_nodes: typing.Dict[int, typing.Any] = {
            n.index: n for n in nodes
        }
        # Maps parse-index → scene item for edge drawing and selection.
        # Includes NodeItem, DotItem, and BackdropItem (all are selectable).
        index_to_item: typing.Dict[int, QtWidgets.QGraphicsItem] = {}

        # Pass 1: backdrops (zValue -2, behind everything)
        for node_data in nodes:
            if node_data.node_type.lower() in _BACKDROP_TYPES:
                item = BackdropItem(node_data)
                self.scene.addItem(item)
                index_to_item[node_data.index] = item

        # Pass 2: regular nodes and dots
        for node_data in nodes:
            nt = node_data.node_type.lower()
            if nt in _BACKDROP_TYPES:
                continue
            if nt in _STACK_EXEMPT_TYPES:
                continue
            if nt in _HIDDEN_NODE_TYPES:
                continue  # hidden — skip rendering, connections drawn through
            if nt == "dot":
                item = DotItem(node_data)
            else:
                item = NodeItem(node_data)
            self.scene.addItem(item)
            index_to_item[node_data.index] = item

        # Fix positions for nodes that have no xpos/ypos in the file (land at
        # 0,0 by default). Place them near their first available parent so the
        # graph stays readable instead of having wires flying to the origin.
        _ORIGIN_THRESHOLD = 1.0  # treat positions within 1 unit of 0,0 as unset
        for node_data in nodes:
            item = index_to_item.get(node_data.index)
            if item is None:
                continue
            if abs(node_data.xpos) <= _ORIGIN_THRESHOLD and abs(node_data.ypos) <= _ORIGIN_THRESHOLD:
                # Find the first connected parent that has a real position
                for parent_idx in node_data.parent_indices:
                    if parent_idx == _NULL_INPUT:
                        continue
                    parent_item = index_to_item.get(parent_idx)
                    if parent_item is None:
                        continue
                    pr = parent_item.sceneBoundingRect()
                    # Place slightly below and to the right of the parent
                    item.setPos(pr.center().x() + 40, pr.bottom() + 80)
                    break

        # Build a by-index lookup for connection resolution
        node_by_index: typing.Dict[int, typing.Any] = {n.index: n for n in nodes}

        def _resolve_visible_parent(parent_idx: int) -> typing.Optional[int]:
            """
            Walk up the parent chain skipping hidden nodes until we reach
            a visible one (present in index_to_item) or run out of parents.
            This makes edges from hidden intermediaries connect directly
            between the nearest visible ancestors and descendants.
            """
            visited: typing.Set[int] = set()
            idx = parent_idx
            while idx is not None and idx not in visited:
                visited.add(idx)
                if idx in index_to_item:
                    return idx
                nd = node_by_index.get(idx)
                if nd is None or not nd.parent_indices:
                    return None
                # Follow slot 0 (primary input) of the hidden node upward
                next_idx = nd.parent_indices[0]
                if next_idx == _NULL_INPUT:
                    return None
                idx = next_idx
            return None

        # Pass 3: edges — resolve through hidden nodes so connections remain
        # visible even when intermediate nodes are not rendered
        for node_data in nodes:
            child = index_to_item.get(node_data.index)
            if child is None:
                continue
            num_slots = node_data.input_count
            for slot, parent_idx in enumerate(node_data.parent_indices):
                if parent_idx == _NULL_INPUT:
                    continue
                # Resolve through any hidden intermediaries
                resolved_idx = _resolve_visible_parent(parent_idx)
                if resolved_idx is None:
                    continue
                parent = index_to_item.get(resolved_idx)
                if parent is not None:
                    self.scene.addItem(EdgeItem(parent, child, slot=slot, num_slots=num_slots))

        # Frame the view on the node content with a comfortable margin.
        # We do NOT call setSceneRect here — the infinite canvas rect set in
        # __init__ must remain unchanged so panning stays unconstrained.
        M      = 200
        bounds = self.scene.itemsBoundingRect()
        self.fitInView(bounds.adjusted(-M, -M, M, M), QtCore.Qt.KeepAspectRatio)

    # ── Import ───────────────────────────────────────────────────────────────

    def import_selected(self) -> None:
        """
        Reconstruct a syntactically valid .nk snippet for the selected nodes
        and paste it into the live Nuke session.

        WRITE-STACK ALGORITHM (three passes):

        PASS 1 — dry-run simulation with NO pre-saving:
          Walk the selected nodes in parse order. Simulate the write_stack
          as Nuke's reader would see it. For every slot where the required
          parent is not found on the stack, record it as a NOTFOUND.

        PASS 2 — build presave set:
          Every node index that appeared as a NOTFOUND target must be
          pre-saved with `set VAR [stack 0]` immediately after it is written,
          before any other node consumes it from the stack.

          WHY THIS IS BETTER THAN COUNT-BASED PRESAVING:
          The old algorithm presaved nodes referenced by >1 consumer. This
          missed nodes that are single-ref but consumed by an INTERMEDIATE
          node before their intended consumer gets to read them — a common
          pattern with Dot nodes feeding multi-input nodes across long chains.
          The simulation-based approach catches every case exactly.

        PASS 3 — emit the file:
          Write the .nk snippet with correct push/set directives before each
          node block, and pre-save directives after each node that needs them.

        SLOT ORDERING:
          Slots are pushed highest-first so slot 0 ends up on top of the
          stack when Nuke reads the node block (slot 0 = first pop = top).
        """
        # Collect all selected scene items, split into compositing nodes
        # (NodeItem + DotItem) and backdrops (BackdropItem).
        # Backdrops are appended verbatim AFTER the compositing snippet —
        # they have inputs=0 so they never touch the write-stack.
        all_selected = self.scene.selectedItems()
        selected_items = [
            i for i in all_selected
            if isinstance(i, (NodeItem, DotItem))
            and i.node_data.node_type.lower() not in _STACK_EXEMPT_TYPES
        ]
        selected_backdrops = [
            i for i in all_selected
            if isinstance(i, BackdropItem)
        ]
        if not selected_items and not selected_backdrops:
            return

        # Sort upstream → downstream (parse order = correct stack order)
        selected_items.sort(key=lambda x: x.node_data.index)
        sel_indices: typing.Set[int] = {item.node_data.index for item in selected_items}

        # Auto-include hidden intermediary nodes (e.g. add_layer) that sit
        # between two selected nodes. These are invisible in the graph view
        # but must be present in the export for connections to be correct.
        # Walk every selected node's parent slots — if a parent is a hidden
        # type whose own parent IS in the selection, pull it in automatically.
        all_nodes_by_index = {
            item.node_data.index: item.node_data
            for item in self.scene.items()
            if isinstance(item, (NodeItem, DotItem, BackdropItem))
        }
        # Also include nodes not in the scene (hidden types were never added)
        # so we need the full parsed node list — access via graph_view storage
        # isn't available here, but we can resolve from parent_indices chain.
        # We iterate until no new hidden nodes are discovered.
        changed = True
        while changed:
            changed = False
            for idx in list(sel_indices):
                nd = all_nodes_by_index.get(idx)
                # nd may be None for hidden nodes — skip, they have no item
                if nd is None:
                    continue
                for parent_idx in nd.parent_indices:
                    if parent_idx == _NULL_INPUT or parent_idx in sel_indices:
                        continue
                    # Check if this parent is a hidden node type by looking at
                    # scene items — hidden nodes have no item, but we can find
                    # them via the _resolve_hidden helper below
                    # For now we handle this in the node_data_by_index path
                    pass

        # Build a full node index from ALL nodes in the parsed graph.
        # We get this by querying parent_indices of existing items and
        # resolving hidden nodes that were never given scene items.
        # The cleanest source is the scene's item list + the fact that
        # hidden nodes are excluded from index_to_item in load_nodes.
        # We store the full node list on self for exactly this purpose:
        _all_nodes: typing.Dict[int, typing.Any] = getattr(self, "_all_parsed_nodes", {})

        if _all_nodes:
            changed = True
            while changed:
                changed = False
                for idx in list(sel_indices):
                    nd = _all_nodes.get(idx)
                    if nd is None:
                        continue
                    for parent_idx in nd.parent_indices:
                        if parent_idx == _NULL_INPUT or parent_idx in sel_indices:
                            continue
                        parent_nd = _all_nodes.get(parent_idx)
                        if parent_nd is None:
                            continue
                        # If this parent is a hidden type and its own parent
                        # is in the selection, include it automatically
                        if parent_nd.node_type.lower() in _HIDDEN_NODE_TYPES:
                            # Check if the hidden node's parent is selected
                            for grandparent_idx in parent_nd.parent_indices:
                                if grandparent_idx != _NULL_INPUT and grandparent_idx in sel_indices:
                                    sel_indices.add(parent_idx)
                                    changed = True
                                    break

            # Rebuild selected_items to include the auto-added hidden nodes
            hidden_items_to_add = []
            for idx in sel_indices:
                if not any(i.node_data.index == idx for i in selected_items):
                    nd = _all_nodes.get(idx)
                    if nd is not None:
                        # Create a temporary NodeItem-like wrapper
                        # Hidden nodes are real NukeNode objects — wrap in a
                        # minimal namedtuple so the write-stack code works
                        import collections
                        _FakeItem = collections.namedtuple("_FakeItem", ["node_data"])
                        hidden_items_to_add.append(_FakeItem(node_data=nd))
            selected_items = sorted(
                selected_items + hidden_items_to_add,
                key=lambda x: x.node_data.index,
            )

        nuke_exe = (
            nuke.env.get("executablepath", "/opt/Nuke15.0v1").replace("\\", "/")
            if nuke else "/opt/Nuke15.0v1"
        )

        # ── PASS 1: iterative dry-run — find ALL nodes that need pre-saving ──────
        #
        # A single dry-run pass is not enough: pre-saving node A may change the
        # stack layout so that node B (which was previously reachable) is now
        # at a different depth, potentially causing cascading NOTFOUND errors.
        # We iterate until no new NOTFOUND indices are discovered (converges
        # in practice within 2–3 iterations on real production scripts).
        #
        # Algorithm per iteration:
        #   - Simulate write_stack with the CURRENT presave set
        #   - Collect any indices that are NOTFOUND (not on stack when needed)
        #   - Add them to presave set
        #   - Repeat until stable (no new indices added)

        def _dry_run(
            items: typing.List[NodeItem],
            presave: typing.Set[int],
        ) -> typing.Set[int]:
            """One simulation pass. Returns set of newly found NOTFOUND indices."""
            pv: typing.Dict[int, str] = {idx: f"SR{i}" for i, idx in enumerate(sorted(presave))}
            pe: typing.Set[int] = set()
            ws: typing.List[int] = []
            new_nf: typing.Set[int] = set()

            for item in items:
                nd = item.node_data
                ns = nd.input_count
                sr = self._build_slot_req(nd, sel_indices)

                for slot in range(ns - 1, -1, -1):
                    req = sr[slot]
                    if req is None:
                        ws.append(_NULL_INPUT)
                    elif req in pv and req in pe:
                        ws.append(req)
                    else:
                        d = self._stack_depth(ws, req)
                        if d is None:
                            new_nf.add(req)
                            ws.append(_NULL_INPUT)
                        elif d > 0:
                            ws.append(req)
                        # d == 0: already on top, nothing pushed

                for _ in range(ns):
                    if ws: ws.pop()
                ws.append(nd.index)
                if nd.index in pv:
                    pe.add(nd.index)

            return new_nf

        presave_indices: typing.Set[int] = set()
        for _ in range(20):   # safety cap; always converges in ≤3 in practice
            new_found = _dry_run(selected_items, presave_indices)
            if not new_found:
                break
            presave_indices |= new_found

        # ── PASS 2: assign variable names to presave targets ──────────────────
        presave_vars: typing.Dict[int, str] = {
            idx: f"SR{i}" for i, idx in enumerate(sorted(presave_indices))
        }
        presave_emitted: typing.Set[int] = set()
        var_counter = len(presave_vars)  # start counter past presave names

        # ── PASS 3: emit the file ─────────────────────────────────────────────
        file_lines: typing.List[str] = [f"#! {nuke_exe} -nx", ""]
        write_stack = []
        group_var_counter: typing.List[int] = [0]

        for item in selected_items:
            nd       = item.node_data
            ns       = nd.input_count
            slot_req = self._build_slot_req(nd, sel_indices)

            # Emit push/set directives for each slot (highest slot first)
            for slot in range(ns - 1, -1, -1):
                req = slot_req[slot]

                if req is None:
                    # Disconnected or external input
                    file_lines.append("push 0")
                    write_stack.append(_NULL_INPUT)

                elif req in presave_vars and req in presave_emitted:
                    # Pre-saved node: push via its variable (always available)
                    file_lines.append(f"push ${presave_vars[req]}")
                    write_stack.append(req)

                else:
                    depth = self._stack_depth(write_stack, req)
                    if depth is None:
                        # Should not happen after pass 1 analysis — defensive
                        file_lines.append("push 0")
                        write_stack.append(_NULL_INPUT)
                        if nuke:
                            nuke.warning(  # type: ignore[union-attr]
                                f"[NodesImport] Unexpected NOTFOUND for "
                                f"'{nd.name}' slot {slot} — wiring may be wrong"
                            )
                    elif depth == 0:
                        # Already on top — Nuke will consume it correctly
                        pass
                    else:
                        # Reorder: bring to top with set/push
                        vn = f"SR{var_counter}"; var_counter += 1
                        file_lines.append(f"set {vn} [stack {depth}]")
                        file_lines.append(f"push ${vn}")
                        write_stack.append(req)

            # Emit the node content block
            node_content = nd.content
            if nd.node_type.lower() in _FLAT_GROUP_TYPES:
                node_content = _rewrite_group_vars(node_content, nd.name, group_var_counter)
            file_lines.append(node_content)
            file_lines.append("")

            # Update write_stack: pop inputs, push self
            for _ in range(ns):
                if write_stack: write_stack.pop()
            write_stack.append(nd.index)

            # Emit pre-save directive immediately after this node is pushed
            if nd.index in presave_vars:
                file_lines.append(f"set {presave_vars[nd.index]} [stack 0]")
                presave_emitted.add(nd.index)

        # Append selected backdrops verbatim — inputs=0, no stack interaction.
        for bd_item in selected_backdrops:
            file_lines.append(bd_item.node_data.content)
            file_lines.append("")

        full_content = "\n".join(file_lines)

        fd, tmp_path = tempfile.mkstemp(suffix=".nk")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(full_content)
            if nuke:
                for n in nuke.allNodes():
                    n.setSelected(False)
                nuke.nodePaste(tmp_path)
                self._post_paste_reconnect(selected_items)
        finally:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

    # ── Import helpers ────────────────────────────────────────────────────────

    @staticmethod
    def _build_slot_req(
        nd: typing.Any,
        sel_indices: typing.Set[int],
    ) -> typing.List[typing.Optional[int]]:
        """
        For each input slot of `nd`, return the parent index if it is in the
        selection, or None if it is disconnected / external.
        """
        result: typing.List[typing.Optional[int]] = []
        for slot in range(nd.input_count):
            if slot < len(nd.parent_indices):
                raw = nd.parent_indices[slot]
                result.append(raw if (raw != _NULL_INPUT and raw in sel_indices) else None)
            else:
                result.append(None)
        return result

    @staticmethod
    def _stack_depth(stack: typing.List[int], target: int) -> typing.Optional[int]:
        """
        Return the depth of `target` in `stack` (0 = top), or None if absent.
        Recomputed fresh so callers always get the current state after any
        pushes within the same slot-loop iteration.
        """
        for i in range(len(stack) - 1, -1, -1):
            if stack[i] == target:
                return len(stack) - 1 - i
        return None

    def _post_paste_reconnect(
        self, imported_items: typing.List[typing.Any]
    ) -> None:
        """
        Re-wire pasted nodes using name-based lookup.

        nodePaste already wires nodes from the stack directives we wrote.
        This pass calls setInput explicitly for every in-selection connection
        as a safety net — if any stack directive was wrong, setInput corrects it.

        External parents (not in selection) are never touched here; nodePaste
        handled them via `push 0` (disconnected), which is the correct behaviour.

        Name collision handling: if Nuke renamed a node after paste (e.g.
        Blur1 → Blur2 due to an existing node with the same name), we cannot
        safely reconnect it and emit a warning instead.
        """
        if not nuke:
            return

        pasted   = nuke.selectedNodes()
        by_name  = {n.name(): n for n in pasted}
        by_index: typing.Dict[int, typing.Any] = {}

        for item in imported_items:
            nk_node = by_name.get(item.node_data.name)
            if nk_node is not None:
                by_index[item.node_data.index] = nk_node
            else:
                nuke.warning(  # type: ignore[union-attr]
                    f"[NodesImport] Could not match '{item.node_data.name}' "
                    f"after paste — possible name collision. Reconnection skipped."
                )

        for item in imported_items:
            nk_node = by_index.get(item.node_data.index)
            if nk_node is None:
                continue
            for slot, parent_idx in enumerate(item.node_data.parent_indices):
                if parent_idx == _NULL_INPUT:
                    continue  # Disconnected slot — leave as-is
                parent_nk = by_index.get(parent_idx)
                if parent_nk is not None:
                    try:
                        nk_node.setInput(slot, parent_nk)
                    except Exception as exc:
                        nuke.warning(  # type: ignore[union-attr]
                            f"[NodesImport] setInput({slot}) failed on "
                            f"'{item.node_data.name}': {exc}"
                        )
